from __future__ import annotations

import hashlib
import json
import os
import sys
from contextlib import contextmanager
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from tests.course_v4_fixture import write_v4_fixture

SKILL_ROOT = (
    Path(__file__).resolve().parents[1]
    / "plugins/python-library-course-builder/skills/building-python-library-courses"
)
sys.path.insert(0, str(SKILL_ROOT / "scripts"))

import verify_v4_course as verifier  # noqa: E402
from scaffold_v4_course import scaffold_v4_pair  # noqa: E402
from verify_learning_project import verify  # noqa: E402
from verify_v4_course import (  # noqa: E402
    V4VerificationError,
    _load_runner_module,
    validate_v4_receipt,
    verify_v4_course,
)


def test_v4_verifier_runs_one_red_green_and_api_acceptance(
    tmp_path: Path,
) -> None:
    route_path, packages, _route = write_v4_fixture(tmp_path / "source")
    learner = tmp_path / "tiny-parser"
    scaffold_v4_pair(route_path, packages, learner)

    receipt = verify_v4_course(learner)
    author = tmp_path / "tiny-parser-author"
    written = json.loads((author / "verification.json").read_text())

    assert receipt == written
    assert receipt["passed"] is True
    assert receipt["profile"] == "course-acceptance-v1"
    assert receipt["checks"]["starter_red"]["selectors"] == 2
    assert receipt["checks"]["solution_green"]["selectors"] == 4
    assert receipt["checks"]["starter_red"]["isolated"] is True
    assert receipt["checks"]["starter_red"]["batches"] == 1
    assert receipt["checks"]["solution_green"]["isolated"] is True
    assert receipt["checks"]["solution_green"]["batches"] == 1
    assert len(receipt["checks"]["starter_red"]["collected"]) == 2
    assert receipt["checks"]["starter_red"]["collected_count"] == 2
    assert len(receipt["checks"]["solution_green"]["collected"]) == 4
    assert receipt["checks"]["solution_green"]["collected_count"] == 4
    assert set(receipt["checks"]["starter_red"]["outcomes"].values()) == {
        "failed"
    }
    assert receipt["checks"]["starter_red"]["task_outcomes"] == {
        "lab01/lab01.q1": ["failed"],
        "lab02/lab02.q1": ["failed"],
    }
    assert set(receipt["checks"]["solution_green"]["outcomes"].values()) == {
        "passed"
    }
    assert receipt["checks"]["api_flow"]["chapters"] == 3
    assert receipt["checks"]["api_flow"]["coding_smoke"] == {
        "chapter_id": "lab01",
        "task_id": "lab01.q1",
        "runs": 2,
    }
    assert receipt["checks"]["api_flow"]["navigation_checks"] == 7
    assert receipt["checks"]["examples"]["executed"] is False
    assert receipt["checks"]["examples"]["required"] is False
    assert receipt["checks"]["node_install"] is False
    assert len(receipt["receipt_sha256"]) == 64
    verifier_script = SKILL_ROOT / "scripts/verify_v4_course.py"
    assert receipt["verifier_sha256"] != hashlib.sha256(
        verifier_script.read_bytes()
    ).hexdigest()
    assert validate_v4_receipt(learner) == receipt

    dispatched = verify(learner, full=True)
    assert dispatched["passed"] is True
    assert dispatched["per_course_node_checks"] is False
    assert dispatched["full_reused_shared_engine_conformance"] is True

    state_path = learner / ".coursekit/state.json"
    with _load_runner_module(
        learner,
        author,
        state_path=state_path,
    ) as module, TestClient(module.create_app()) as client:
        answered = client.post(
            "/api/knowledge/answer",
            json={
                "lab_id": "lab00",
                "question_id": "lab00.k1",
                "choice_id": "a",
            },
        )
        assert answered.status_code == 200
        assert answered.json()["correct"] is True
    assert state_path.is_file()
    assert state_path.with_name("state.json.lock").is_file()
    assert validate_v4_receipt(learner) == receipt

    metadata = learner / "tiny_parser.egg-info/PKG-INFO"
    metadata.parent.mkdir()
    metadata.write_text("Generated by learner environment setup.\n", encoding="utf-8")
    assert validate_v4_receipt(learner) == receipt

    lock = learner / "uv.lock"
    lock.write_text(
        "version = 1\nrevision = 3\n",
        encoding="utf-8",
    )
    with pytest.raises(V4VerificationError, match="learner_tree_sha256"):
        validate_v4_receipt(learner)


def test_v4_verifier_tests_cannot_mutate_learner_or_canonical_tests(
    tmp_path: Path,
) -> None:
    route_path, packages, _route = write_v4_fixture(tmp_path / "source")
    public_test = packages / "lab01/tests/public/test_normalize.py"
    public_test.write_text(
        public_test.read_text(encoding="utf-8").replace(
            "def test_normalize():\n",
            "def test_normalize():\n"
            "    from pathlib import Path\n"
            "    Path('src/tiny_parser/normalize.py').write_text("
            "'MUTATED = True\\n')\n"
            "    Path('LEARNER_TEST_RAN').write_text('bad')\n"
            "    Path(__file__).with_name('CANONICAL_TEST_MUTATED').write_text("
            "'bad')\n",
        ),
        encoding="utf-8",
    )
    learner = tmp_path / "tiny-parser"
    scaffold_v4_pair(route_path, packages, learner)
    starter = learner / "src/tiny_parser/normalize.py"
    canonical = learner / "tests/lab01/test_normalize.py"
    starter_before = starter.read_bytes()
    canonical_before = canonical.read_bytes()

    receipt = verify_v4_course(learner)

    assert receipt["passed"] is True
    assert starter.read_bytes() == starter_before
    assert canonical.read_bytes() == canonical_before
    assert not (learner / "LEARNER_TEST_RAN").exists()
    assert not (
        learner / "tests/lab01/CANONICAL_TEST_MUTATED"
    ).exists()


def test_v4_starter_red_allows_mixed_outcomes_within_each_task(
    tmp_path: Path,
) -> None:
    route_path, packages, route = write_v4_fixture(tmp_path / "source")
    lab01_task = route["chapters"][1]["task_contracts"][0]
    lab01_task["public_tests"].append(
        "test_normalize.py::test_symbol_is_available"
    )
    route_path.write_text(
        json.dumps(route, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    public_test = packages / "lab01/tests/public/test_normalize.py"
    public_test.write_text(
        public_test.read_text(encoding="utf-8")
        + "\n\ndef test_symbol_is_available():\n"
        "    assert callable(normalize)\n",
        encoding="utf-8",
    )
    learner = tmp_path / "tiny-parser"
    scaffold_v4_pair(route_path, packages, learner)

    receipt = verify_v4_course(learner)

    assert receipt["checks"]["starter_red"]["selectors"] == 3
    assert receipt["checks"]["starter_red"]["task_outcomes"] == {
        "lab01/lab01.q1": ["failed", "passed"],
        "lab02/lab02.q1": ["failed"],
    }


def test_v4_starter_red_requires_every_declared_task_to_fail(
    tmp_path: Path,
) -> None:
    route_path, packages, _route = write_v4_fixture(tmp_path / "source")
    starter = packages / "lab01/starter/src/tiny_parser/normalize.py"
    starter.write_text(
        "def normalize(value: str) -> str:\n"
        "    return value.strip()\n",
        encoding="utf-8",
    )
    learner = tmp_path / "tiny-parser"
    scaffold_v4_pair(route_path, packages, learner)

    with pytest.raises(V4VerificationError, match="lab01.q1 did not start RED"):
        verify_v4_course(learner)


def test_v4_starter_red_rejects_setup_errors_or_missing_outcomes(
    tmp_path: Path,
) -> None:
    route_path, packages, _route = write_v4_fixture(tmp_path / "source")
    public_test = packages / "lab01/tests/public/test_normalize.py"
    public_test.write_text(
        public_test.read_text(encoding="utf-8").replace(
            "def test_normalize():",
            "def test_normalize(missing_fixture):",
        ),
        encoding="utf-8",
    )
    learner = tmp_path / "tiny-parser"
    scaffold_v4_pair(route_path, packages, learner)

    with pytest.raises(V4VerificationError, match="collect every selector"):
        verify_v4_course(learner)


def test_v4_verifier_rejects_runtime_task_projection_omission(
    tmp_path: Path,
) -> None:
    route_path, packages, _route = write_v4_fixture(tmp_path / "source")
    learner = tmp_path / "tiny-parser"
    scaffold_v4_pair(route_path, packages, learner)
    course_path = learner / ".coursekit/course.json"
    course = json.loads(course_path.read_text(encoding="utf-8"))
    for collection in ("chapters", "labs"):
        lab02 = next(
            chapter
            for chapter in course[collection]
            if chapter["id"] == "lab02"
        )
        lab02["graded"] = False
        lab02["tasks"] = []
        lab02["questions"] = []
    course_path.write_text(
        json.dumps(course, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    with pytest.raises(V4VerificationError, match="public projection"):
        verify_v4_course(learner)


@pytest.mark.parametrize(
    "relative",
    [
        "solution/src/tiny_parser/private.py",
        "tests/hidden/lab01/test_private.py",
        "tests/lab01/nested/hidden/test_private.py",
        "tests/lab01/test_private_hidden.py",
        "quiz-answers.json",
        "author.json",
    ],
)
def test_v4_verifier_rejects_private_material_in_learner_projection(
    tmp_path: Path,
    relative: str,
) -> None:
    route_path, packages, _route = write_v4_fixture(tmp_path / "source")
    learner = tmp_path / "tiny-parser"
    scaffold_v4_pair(route_path, packages, learner)
    leaked = learner / relative
    leaked.parent.mkdir(parents=True, exist_ok=True)
    leaked.write_text("private material must not ship\n", encoding="utf-8")

    with pytest.raises(V4VerificationError, match="private author material"):
        verify_v4_course(learner)


def test_v4_verifier_rejects_graded_flag_inconsistent_with_kind(
    tmp_path: Path,
) -> None:
    route_path, packages, _route = write_v4_fixture(tmp_path / "source")
    learner = tmp_path / "tiny-parser"
    scaffold_v4_pair(route_path, packages, learner)
    course_path = learner / "course.toml"
    course_path.write_text(
        course_path.read_text(encoding="utf-8").replace(
            'kind = "orientation"\ngraded = false',
            'kind = "orientation"\ngraded = true',
            1,
        ),
        encoding="utf-8",
    )

    with pytest.raises(V4VerificationError, match="graded flag"):
        verify_v4_course(learner)


@pytest.mark.parametrize("tamper", ["generation", "runtime"])
def test_v4_verifier_rejects_stale_or_tampered_runtime_contract(
    tmp_path: Path,
    tamper: str,
) -> None:
    route_path, packages, _route = write_v4_fixture(tmp_path / "source")
    learner = tmp_path / "tiny-parser"
    scaffold_v4_pair(route_path, packages, learner)
    if tamper == "generation":
        generation_path = learner / ".coursekit/generation.json"
        generation = json.loads(generation_path.read_text(encoding="utf-8"))
        generation["runtime_contract_sha256"] = "0" * 64
        generation_path.write_text(
            json.dumps(
                generation,
                ensure_ascii=False,
                indent=2,
                sort_keys=True,
            )
            + "\n",
            encoding="utf-8",
        )
        expected = "current runtime contract"
    else:
        runner = learner / "coursekit_runtime/runner.py"
        runner.write_text(
            runner.read_text(encoding="utf-8") + "\n# untrusted mutation\n",
            encoding="utf-8",
        )
        expected = "trusted projection"

    with pytest.raises(V4VerificationError, match=expected):
        verify_v4_course(learner)


def test_v4_verifier_preflights_nested_symlink_before_copy(
    tmp_path: Path,
) -> None:
    route_path, packages, _route = write_v4_fixture(tmp_path / "source")
    learner = tmp_path / "tiny-parser"
    scaffold_v4_pair(route_path, packages, learner)
    author = tmp_path / "tiny-parser-author"
    outside = tmp_path / "outside.py"
    outside.write_text("raise RuntimeError('must never execute')\n", encoding="utf-8")
    link = author / "solution/src/tiny_parser/nested_escape.py"
    try:
        link.symlink_to(outside)
    except OSError as error:  # pragma: no cover - restricted Windows builders
        pytest.skip(f"symlinks are unavailable: {error}")

    with pytest.raises(V4VerificationError, match="author tree contains a symlink"):
        verify_v4_course(learner)


def test_v4_verifier_rejects_executable_bytecode_cache(
    tmp_path: Path,
) -> None:
    route_path, packages, _route = write_v4_fixture(tmp_path / "source")
    learner = tmp_path / "tiny-parser"
    scaffold_v4_pair(route_path, packages, learner)
    cache = learner / "coursekit_runtime/__pycache__"
    cache.mkdir()
    (cache / "runner.cpython-313.pyc").write_bytes(b"untrusted bytecode")

    with pytest.raises(V4VerificationError, match="executable bytecode cache"):
        verify_v4_course(learner)


@pytest.mark.parametrize("projection", ["learner", "author", "runtime"])
def test_v4_offline_receipt_rejects_injected_bytecode_cache(
    tmp_path: Path,
    projection: str,
) -> None:
    route_path, packages, _route = write_v4_fixture(tmp_path / "source")
    learner = tmp_path / "tiny-parser"
    scaffold_v4_pair(route_path, packages, learner)
    receipt = verify_v4_course(learner)
    assert validate_v4_receipt(learner) == receipt
    author = tmp_path / "tiny-parser-author"
    if projection == "learner":
        cache = learner / "src/tiny_parser/__pycache__"
    elif projection == "author":
        cache = author / "solution/src/tiny_parser/__pycache__"
    else:
        cache = learner / "coursekit_runtime/__pycache__"
    cache.mkdir(parents=True)
    (cache / "injected.cpython-313.pyc").write_bytes(b"untrusted bytecode")

    with pytest.raises(V4VerificationError, match="executable bytecode cache"):
        validate_v4_receipt(learner)


def test_v4_verifier_rejects_premature_navigation_unlock(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    route_path, packages, _route = write_v4_fixture(tmp_path / "source")
    learner = tmp_path / "tiny-parser"
    scaffold_v4_pair(route_path, packages, learner)
    real_loader = verifier._load_runner_module

    @contextmanager
    def prematurely_unlocked_loader(
        learner_root: Path,
        author_root: Path,
        *,
        state_path: Path | None = None,
    ):
        with real_loader(
            learner_root,
            author_root,
            state_path=state_path,
        ) as module:
            real_exposed_state = module.exposed_state

            def expose_every_chapter(value):
                state = real_exposed_state(value)
                state["unlocked_labs"] = [
                    chapter["id"] for chapter in module.manifest()["chapters"]
                ]
                return state

            module.exposed_state = expose_every_chapter
            yield module

    monkeypatch.setattr(
        verifier,
        "_load_runner_module",
        prematurely_unlocked_loader,
    )

    with pytest.raises(V4VerificationError, match="navigation gate state"):
        verify_v4_course(learner)


def test_v4_verifier_restores_environment_and_does_not_gate_on_examples(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    route_path, packages, _route = write_v4_fixture(tmp_path / "source")
    guard = packages / "lab01/examples/optional_broken_example.py"
    guard.write_text(
        "raise RuntimeError('examples are optional acceptance artifacts')\n",
        encoding="utf-8",
    )
    learner = tmp_path / "tiny-parser"
    scaffold_v4_pair(route_path, packages, learner)
    sentinels = {
        "COURSEKIT_LEARNER_ROOT": "existing-learner",
        "COURSEKIT_ROOT": "existing-root",
        "COURSEKIT_COURSE_DIR": "existing-course-dir",
        "COURSEKIT_AUTHOR_ROOT": "existing-author",
        "COURSEKIT_STATE_PATH": "existing-state",
    }
    for name, value in sentinels.items():
        monkeypatch.setenv(name, value)
    modules_before = {
        name for name in sys.modules if name.startswith("_coursekit_v4_runtime_")
    }

    receipt = verify_v4_course(learner)

    assert receipt["passed"] is True
    assert receipt["checks"]["examples"] == {
        "count": 3,
        "executed": False,
        "required": False,
    }
    assert {name: os.environ.get(name) for name in sentinels} == sentinels
    assert {
        name for name in sys.modules if name.startswith("_coursekit_v4_runtime_")
    } == modules_before


def test_v4_optional_quiz_prose_passes_acceptance_and_runner(
    tmp_path: Path,
) -> None:
    route_path, packages, _route = write_v4_fixture(tmp_path / "source")
    for chapter_id in ("lab00", "lab01", "lab02"):
        quiz_path = packages / chapter_id / "quiz.json"
        quiz = json.loads(quiz_path.read_text(encoding="utf-8"))
        for question in quiz["questions"]:
            question.pop("explanation", None)
            for choice in question["choices"]:
                choice.pop("feedback", None)
        quiz_path.write_text(
            json.dumps(quiz, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
    learner = tmp_path / "tiny-parser"
    scaffold_v4_pair(route_path, packages, learner)

    receipt = verify_v4_course(learner)

    assert receipt["passed"] is True
    author = tmp_path / "tiny-parser-author"
    with _load_runner_module(
        learner,
        author,
        state_path=learner / ".coursekit/state.json",
    ) as module, TestClient(module.create_app()) as client:
        response = client.post(
            "/api/knowledge/answer",
            json={
                "lab_id": "lab00",
                "question_id": "lab00.k1",
                "choice_id": "a",
            },
        )
    assert response.status_code == 200
    assert response.json().get("feedback") in {"", None}
    assert response.json().get("explanation") in {"", None}
